name:                yampa-brick
version:             0.1.0.0
github:              "vitalibarozzi/yampa-brick"
license:             BSD-3-Clause
author:              "J. V. Vitali Barozzi"
maintainer:          "vitalivitor@gmail.com"
copyright:           "2024 J. V. Vitali Barozzi"


dependencies:
- base  >= 4.7    && < 5
- Yampa >= 0.14.5 && < 1
- brick >= 1.9    && < 2
- vty   >= 5.38   && < 6
- text  >= 2.0.2  && < 3


ghc-options:
#- -Werror
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints


library:
  source-dirs: src


tests:
  yampa-brick-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yampa-brick
